[run]
build = "npm run build"

[gptengineer-app]
project_id = "39aed5c7-6041-4882-8d18-4de49f9b13b0"

[[gptengineer-app.openapi]]
url = "https://mnwefvnykbgyhbdzpleh.supabase.co/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ud2Vmdm55a2JneWhiZHpwbGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTMyNzQ3MzQsImV4cCI6MjAyODg1MDczNH0.tnHysd1LqayzpQ1L-PImcvlkUmkNvocpMS7tS-hYZNg"
